name: WirelessChests
main: com.resbah.WirelessChests.WirelessChests
version: 0.0.3-ALPHA by resba
commands:
    wc:
        description: Creates stone above the player's head
        usage: /wc
    namechest:
        description: Creates a chest below the user and returns variables
        usage: /namechest [name] [group] [default]
    sync:
        description: basic usage of sync
        usage: /sync [group]