name: WirelessChests
main: com.resbah.WirelessChests.WirelessChests
version: 0.0.3-ALPHA by resba
commands:
    wcaddchest:
        description: Creates a chest below the user and returns variables
        usage: /namechest [name] [group]
    wcsync:
        description: basic usage of sync
        usage: /sync [group]
    wcsetmain:
        description: Sets a chest as Main Chest
        usage: /dchest [name] [group]
    wcrem:
        description: Remove Chest. (If the chest is a main chest, then it's removed from the list)
        usage: /wcrem [name] [group]
    wcabout:
        description: Displays Version Information and Relative info.