name: WirelessChests
main: com.resbah.WirelessChests.WirelessChests
version: 0.0.1-ALPHA by resba
commands:
    wc:
        description: Demo Command that can only be seen by the user
        usage: /wc
    wc2:
        description: Demo Command that can be sent by the console as well as a user
        usage: /wc2