name: WirelessChests
main: com.resbah.WirelessChests.WirelessChests
version: 0.0.1-ALPHA by resba
commands:
    wc:
        description: Demo Command that can only be seen by the user
        usage: /wc